In [1]:
import pandas as pd

df_hits = pd.read_parquet('data/diploma_main_dataset/ga_hits.parquet.gz')
df_sessions = pd.read_parquet('data/diploma_main_dataset/ga_session.parquet.gz')

## Общая информация

In [14]:
df_sessions.head()

,session_id,client_id,visit_date,visit_time,visit_number,utm_source,utm_medium,utm_campaign,utm_adcontent,utm_keyword,device_category,device_os,device_brand,device_model,device_screen_resolution,device_browser,geo_country,geo_city
0,9055434745589932991.1637753792.1637753792,2108382700.1637753791,2021-11-24,14:36:32,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,mobile,Android,Huawei,None,360x720,Chrome,Russia,Zlatoust
1,905544597018549464.1636867290.1636867290,210838531.1636867288,2021-11-14,08:21:30,1,MvfHsxITijuriZxsqZqt,cpm,FTjNLDyTrXaWYgZymFkV,xhoenQgDQsgfEPYNPwKO,IGUCNvHlhfHpROGclCit,mobile,Android,Samsung,None,385x854,Samsung Internet,Russia,Moscow
2,9055446045651783499.1640648526.1640648526,2108385331.1640648523,2021-12-28,02:42:06,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,mobile,Android,Huawei,None,360x720,Chrome,Russia,Krasnoyarsk
3,9055447046360770272.1622255328.1622255328,2108385564.1622255328,2021-05-29,05:00:00,1,kjsLglQLzykiRbcDiGcD,cpc,None,NOBKLgtuvqYWkXQHeYWM,None,mobile,None,Xiaomi,None,393x786,Chrome,Russia,Moscow
4,9055447046360770272.1622255345.1622255345,2108385564.1622255328,2021-05-29,05:00:00,2,kjsLglQLzykiRbcDiGcD,cpc,None,None,None,mobile,None,Xiaomi,None,393x786,Chrome,Russia,Moscow

In [9]:
df_sessions.info()
df_sessions.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1860042 entries, 0 to 1860041
Data columns (total 18 columns):
 #   Column                    Dtype
---  ------                    -----
 0   session_id                object
 1   client_id                 object
 2   visit_date                object
 3   visit_time                object
 4   visit_number              int64
 5   utm_source                object
 6   utm_medium                object
 7   utm_campaign              object
 8   utm_adcontent             object
 9   utm_keyword               object
 10  device_category           object
 11  device_os                 object
 12  device_brand              object
 13  device_model              object
 14  device_screen_resolution  object
 15  device_browser            object
 16  geo_country               object
 17  geo_city                  object
dtypes: int64(1), object(17)
memory usage: 255.4+ MB

(1860042, 18)

In [15]:
df_hits.head()

,session_id,hit_date,hit_time,hit_number,hit_type,hit_referer,hit_page_path,event_category,event_action,event_label,event_value
0,5639623078712724064.1640254056.1640254056,2021-12-23,597864.0,30,event,None,sberauto.com/cars?utm_source_initial=google&ut...,quiz,quiz_show,None,NaN
1,7750352294969115059.1640271109.1640271109,2021-12-23,597331.0,41,event,None,sberauto.com/cars/fiat?city=1&city=18&rental_c...,quiz,quiz_show,None,NaN
2,885342191847998240.1640235807.1640235807,2021-12-23,796252.0,49,event,None,sberauto.com/cars/all/volkswagen/polo/e994838f...,quiz,quiz_show,None,NaN
3,142526202120934167.1640211014.1640211014,2021-12-23,934292.0,46,event,None,sberauto.com/cars?utm_source_initial=yandex&ut...,quiz,quiz_show,None,NaN
4,3450086108837475701.1640265078.1640265078,2021-12-23,768741.0,79,event,None,sberauto.com/cars/all/mercedes-benz/cla-klasse...,quiz,quiz_show,None,NaN

In [6]:
df_hits.info()
df_hits.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15726470 entries, 0 to 15726469
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   session_id      object
 1   hit_date        object
 2   hit_time        float64
 3   hit_number      int64
 4   hit_type        object
 5   hit_referer     object
 6   hit_page_path   object
 7   event_category  object
 8   event_action    object
 9   event_label     object
 10  event_value     float64
dtypes: float64(2), int64(1), object(8)
memory usage: 1.3+ GB

(15726470, 11)

## Проверка пропусков

In [12]:
df_sessions.isna().sum()

session_id                        0
client_id                         0
visit_date                        0
visit_time                        0
visit_number                      0
utm_source                       97
utm_medium                        0
utm_campaign                 219603
utm_adcontent                335615
utm_keyword                 1082061
device_category                   0
device_os                   1070138
device_brand                 367178
device_model                1843704
device_screen_resolution          0
device_browser                    0
geo_country                       0
geo_city                          0
dtype: int64

In [22]:
df_hits.isna().sum()

session_id               0
hit_date                 0
hit_time           9160322
hit_number               0
hit_type                 0
hit_referer        6274804
hit_page_path            0
event_category           0
event_action             0
event_label        3760184
event_value       15726470
dtype: int64

In [23]:
for col in df_sessions.columns:
    if df_sessions[col].isna().sum() > 0:
        if df_sessions[col].dtype == 'object':
            most_freq = df_sessions[col].mode()[0]
            df_sessions[col].fillna(most_freq, inplace=True)
        else:
            mean_value = df_sessions[col].mean()
            df_sessions[col].fillna(mean_value, inplace=True)

In [28]:
for col in df_hits.columns:
    if df_hits[col].isna().sum() > 0:
        if df_hits[col].dtype == 'object':
            most_freq = df_hits[col].mode()[0]
            df_hits[col].fillna(most_freq, inplace=True)
        else:
            mean_value = df_hits[col].mean()
            df_hits[col].fillna(mean_value, inplace=True)

In [26]:
df_sessions.isna().sum().sum()

0

In [31]:
df_hits.isna().sum().sum()

15726470

## Проверка дубликатов

In [19]:
df_sessions.duplicated().sum()

0

In [20]:
df_hits.duplicated().sum()

0

## Преобразование дат и времени

In [16]:
df_sessions['visit_date'] = pd.to_datetime(df_sessions['visit_date'], errors='coerce')
df_sessions['visit_time'] = pd.to_datetime(df_sessions['visit_time'], format='%H:%M:%S').dt.time

df_hits['hit_date'] = pd.to_datetime(df_hits['hit_date'], errors='coerce')

In [17]:
df_sessions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1860042 entries, 0 to 1860041
Data columns (total 18 columns):
 #   Column                    Dtype
---  ------                    -----
 0   session_id                object
 1   client_id                 object
 2   visit_date                datetime64[ns]
 3   visit_time                object
 4   visit_number              int64
 5   utm_source                object
 6   utm_medium                object
 7   utm_campaign              object
 8   utm_adcontent             object
 9   utm_keyword               object
 10  device_category           object
 11  device_os                 object
 12  device_brand              object
 13  device_model              object
 14  device_screen_resolution  object
 15  device_browser            object
 16  geo_country               object
 17  geo_city                  object
dtypes: datetime64[ns](1), int64(1), object(16)
memory usage: 255.4+ MB

In [18]:
df_hits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15726470 entries, 0 to 15726469
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   session_id      object
 1   hit_date        datetime64[ns]
 2   hit_time        float64
 3   hit_number      int64
 4   hit_type        object
 5   hit_referer     object
 6   hit_page_path   object
 7   event_category  object
 8   event_action    object
 9   event_label     object
 10  event_value     float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(7)
memory usage: 1.3+ GB

## Сохранение

In [ ]:
df_hits.to_parquet('data/diploma_main_dataset/ga_hits.parquet.gz', compression='gzip', index=False)
df_sessions.to_parquet('data/diploma_main_dataset/ga_session.parquet.gz', compression='gzip', index=False)